### ISSUE TITLE
Add schematics

### ISSUE THREAD

**Issue by coderbyheart** [bifravst/cat-tracker-pcb#1]

**Comment by martinjuhasz** [comment]
Hey! Will there be a BOM and/or Gerber files available for this PCB at some point?
This looks like a stripped down Thingy with just the necessary parts for device tracking?
Would love to be able to build one myself!

**Comment by coderbyheart** [comment]
Hei Martin! Thanks for reaching out, I have passed on your request for the BOM, it will definitely be included with the schematics, but right now I have no ETA when they will be ready.
